import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import Data from "./Data/Data";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import Image from "next/image";
import pic from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 ">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons ">{Data.home.navLogo}</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-point text-xl" />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2
              className="text-5xl text-teal-600 font-medium
            "
            >
              {Data.home.name}
            </h2>
            <h3 className="text-3 py-2">{Data.home.role}</h3>
            <p className="text-medium py-5 leading-8 text-gray-800">
              {Data.home.desc}
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href={Data.socials.twitter}>
              {" "}
              <AiFillTwitterCircle />
            </a>
            <a href={Data.socials.linkedIn}>
              {" "}
              <AiFillLinkedin />
            </a>
            <a href={Data.socials.youtube}>
              {" "}
              <AiFillYoutube />
            </a>
            <a href={Data.socials.github}>
              {" "}
              <AiFillGithub />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={pic} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1">Skills I Have.</h3>
            <p className="text-md py-2 leading-8 text-gray-800">
              I build applications both on the{" "}
              <span className="text-teal-500">Web</span> and on{" "}
              <span className="text-teal-500">Mobile</span> devices using{" "}
              <span className="text-teal-500">React</span> and
              <span className="text-teal-500">Flutter.</span>
            </p>
          </div>
          <div>
            <div className="text-center shadow-lg p-10 rouded-xl my-10">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                {Data.skills.skill_1.title}
              </h3>
              <p className="py-2">{Data.skills.skill_1.desc}</p>
              <h4 className="py-4 text-teal-600">Technologies I use.</h4>
              <div>
                {" "}
                {Data.technologies.map((item) => {
                  return <p className="text-grey-800 py-1  ">{item}</p>;
                })}
              </div>
            </div>{" "}
            <div className="text-center shadow-lg p-10 rouded-xl my-10">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                {Data.skills.skill_1.title}
              </h3>
              <p className="py-2">{Data.skills.skill_1.desc}</p>
              <h4 className="py-4 text-teal-600">Technologies I use.</h4>
              <div>
                {" "}
                {Data.technologies.map((item) => {
                  return <p className="text-grey-800 py-1  ">{item}</p>;
                })}
              </div>
            </div>{" "}
            <div className="text-center shadow-lg p-10 rouded-xl my-10">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                {Data.skills.skill_1.title}
              </h3>
              <p className="py-2">{Data.skills.skill_1.desc}</p>
              <h4 className="py-4 text-teal-600">Technologies I use.</h4>
              <div>
                {" "}
                {Data.technologies.map((item) => {
                  return <p className="text-grey-800 py-1  ">{item}</p>;
                })}
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
